config/routes.rb
Answerbuild::Application.routes.draw do
  root "sessions#new" 
  get 'logout' => 'sessions#destroy', as: :logout
  resources :sessions
  resources :users, except: :destroy
  resources :answers, except: :destroy
  resources :steps

  get 'answers__' => 'answers#index3', as: :index3
  get 'answers_' => 'answers#index2', as: :index2
  get 'automate' => 'answers#automate', as: :automate
  get 'qsee_updates' => 'answers#qsee_updates', as: :qsee_updates
  get 'answers/:id/code' => 'answers#code2', as: :code
  get 'answers/:id/answer' => 'answers#alt_answer', as: :angular
  get 'answers/:id/answer_jp' => 'answers#answer_jp', as: :angular_jp
  get 'answers/:id/inspect' => 'answers#inspect', as: :inspect
  get 'inspect_all' => 'answers#inspect_all', as: :inspect_all
  get 'qsee_rn_array' => 'answers#qsee_rn_array', as: :qsee_rn_array
  get 'qsee_rn_partial/:id' => 'answers#qsee_rn_partial', as: :qsee_rn_partial
  get 'strings' => 'answers#strings', as: :strings
  get 'translate/:id' => 'answers#translate', as: :translate
  get 'translation_portal' => 'answers#translate_index', as: :translate_index
  get 'spreadsheet' => 'answers#spreadsheet', as: :spreadsheet
  get 'answers/:id/preview' => 'answers#preview', as: :preview
  get 'answers/:id/preview_jp' => 'answers#preview_jp', as: :preview_jp
  get 'stepss' => 'steps#index2',as: :imagedump
  get 'qtpojo' => 'answers#qtpojo'

  get 'answers/:id/test' => 'answers#test'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :user
	has_many :steps

	def self.steps
		@steps = Step.where(:answer_id => self.id).order(:number,:updated_at)
	end

	def steps
		steps = []
		@steps = Step.where(:answer_id => self.id).order(:number,:updated_at)
		if self.translation_needed.match('COMPLETE')
			@steps.each_with_index do |step,i|
				steps.push({
				:step_id => step.id,
				:number => step.number, :true_number => i, :step_type => step.step_type, :step => step.step, 
				:step_jp => if step.step_jp.blank? then nil else step.step_jp end, 
				:image_jp => step.image_upload_jp,
				:image => if step.image_upload.blank? then '//'+step.image else step.image_upload end
				})
			end
		elsif self.translation_needed.match('NO')
			@steps.each_with_index do |step,i|
				steps.push({
				:step_id => step.id,
				:number => step.number, :true_number => i, :step_type => step.step_type, :step => step.step,
				:image => if step.image_upload.blank? then '//'+step.image else step.image_upload end
				})
			end
		end
		steps
	end

	def pojo2
		steps = []
		@steps = Step.where(:answer_id => self.id).order(:number,:updated_at)
		if self.translation_needed.match('COMPLETE')
			@steps.each_with_index do |step,i|
				steps.push({:number => step.number, :true_number => i, :step_type => step.step_type, :step => step.clean_step, 
				:step_id => step.id,
				:step_jp => if step.step_jp.blank? then nil else step.clean_step_jp end, 
				:image_jp => step.image_upload_jp,
				:image => if step.image_upload.blank? then '//'+step.image else step.image_upload end
				})
			end
			answer = {
				:series => self.series, :title => self.title, :tagline => self.clean_tagline,
				:title_jp => self.title_jp, :tagline_jp => self.clean_tagline_jp, :steps => steps
			}
		elsif self.translation_needed.match('NO')
			@steps.each_with_index do |step,i|
				steps.push({:number => step.number, :true_number => i, :step_type => step.step_type, :step => step.clean_step, 
				:step_id => step.id,
				:image => if step.image_upload.blank? then '//'+step.image else step.image_upload end
				})
			end
			answer = {
				:series => self.series, :title => self.title, :tagline => self.clean_tagline,
				:steps => steps
			}
		end
		answer
	end

	def pojo
		steps = []
		@steps = Step.where(:answer_id => self.id).order(:number,:updated_at)
		@steps.each_with_index do |step,i|
			steps.push({:number => step.number, :true_number => i, :step_type => step.step_type, :step => step.clean_step, 
			:step_jp => if step.step_jp.blank? then nil else step.clean_step_jp end, 
			:image_jp => step.image_upload_jp,
			:image => if step.image_upload.blank? then '//'+step.image else step.image_upload end
			})
		end
		answer = {
			:series => self.series, :title => self.title, :tagline => self.clean_tagline,
			:title_jp => self.title_jp, :tagline_jp => self.clean_tagline_jp, :steps => steps
		}
		answer
	end

	def clean_tagline
		clean_tagline = self.tagline.gsub(/\[red\]/,'<span class="red">').gsub(/\[\/red\]/,'</span>').gsub(/\[blue\]/,'<span class="blue">').gsub(/\[\/blue\]/,'</span>').gsub(/\[green\]/,'<span class="green">').gsub(/\[\/reen\]/,'</span>').gsub(/\[yellow\]/,'<span class="yellow">').gsub(/\[\/yellow\]/,'</span>').gsub(/\[orange\]/,'<span class="orange">').gsub(/\[\/orange\]/,'</span>').gsub(/\[lgreen\]/,'<span class="lgreen">').gsub(/\[\/lgreen\]/,'</span>').gsub(/\[bold\]/,'<strong>').gsub(/\[\/bold\]/,'</strong>').gsub(/\[i\]/,'<em>').gsub(/\[\/i\]/,'</em>').gsub(/\[u\]/,'<u>').gsub(/\[\/u\]/,'</u>').gsub(/\[br\]/,'<br>').gsub(/\[note\]/,'<div class="inst information_new"><i class="fa fa-3x fa-info-circle"></i><span information_text>').gsub(/\[\/note\]/,'</span></div>').gsub(/\[cat\]/,'<div class="inst cautiondiv_new"><i class="fa fa-3x fa-exclamation-triangle"></i>').gsub(/\[\/cat\]/,'</div>').gsub(/(https|http):\/\/qsee.custhelp.com/,'')

		clean_tagline = video_clean(clean_tagline)

		clean_tagline = clean_tagline.html_safe
		clean_tagline
	end

	def clean_tagline_jp
		if self.tagline_jp.blank?
			clean_tagline = nil
		else
			clean_tagline = self.tagline_jp.gsub(/\[red\]/,'<span class="red">').gsub(/\[\/red\]/,'</span>').gsub(/\[blue\]/,'<span class="blue">').gsub(/\[\/blue\]/,'</span>').gsub(/\[green\]/,'<span class="green">').gsub(/\[\/reen\]/,'</span>').gsub(/\[yellow\]/,'<span class="yellow">').gsub(/\[\/yellow\]/,'</span>').gsub(/\[orange\]/,'<span class="orange">').gsub(/\[\/orange\]/,'</span>').gsub(/\[lgreen\]/,'<span class="lgreen">').gsub(/\[\/lgreen\]/,'</span>').gsub(/\[bold\]/,'<strong>').gsub(/\[\/bold\]/,'</strong>').gsub(/\[i\]/,'<em>').gsub(/\[\/i\]/,'</em>').gsub(/\[u\]/,'<u>').gsub(/\[\/u\]/,'</u>').gsub(/\[br\]/,'<br>').gsub(/\[note\]/,'<div class="inst information_new"><i class="fa fa-3x fa-info-circle"></i><span information_text>').gsub(/\[\/note\]/,'</span></div>').gsub(/\[cat\]/,'<div class="inst cautiondiv_new"><i class="fa fa-3x fa-exclamation-triangle"></i>').gsub(/\[\/cat\]/,'</div>').gsub(/(https|http):\/\/qsee.custhelp.com/,'')	
			clean_tagline = clean_tagline.html_safe
		end
		clean_tagline
	end

	def clean_tagline_fr
		if self.tagline_fr.blank?
			clean_tagline = nil
		else
			clean_tagline = self.tagline_fr.gsub(/\[red\]/,'<span class="red">').gsub(/\[\/red\]/,'</span>').gsub(/\[blue\]/,'<span class="blue">').gsub(/\[\/blue\]/,'</span>').gsub(/\[green\]/,'<span class="green">').gsub(/\[\/reen\]/,'</span>').gsub(/\[yellow\]/,'<span class="yellow">').gsub(/\[\/yellow\]/,'</span>').gsub(/\[orange\]/,'<span class="orange">').gsub(/\[\/orange\]/,'</span>').gsub(/\[lgreen\]/,'<span class="lgreen">').gsub(/\[\/lgreen\]/,'</span>').gsub(/\[bold\]/,'<strong>').gsub(/\[\/bold\]/,'</strong>').gsub(/\[i\]/,'<em>').gsub(/\[\/i\]/,'</em>').gsub(/\[u\]/,'<u>').gsub(/\[\/u\]/,'</u>').gsub(/\[br\]/,'<br>').gsub(/\[note\]/,'<div class="inst information_new"><i class="fa fa-3x fa-info-circle"></i><span information_text>').gsub(/\[\/note\]/,'</span></div>').gsub(/\[cat\]/,'<div class="inst cautiondiv_new"><i class="fa fa-3x fa-exclamation-triangle"></i>').gsub(/\[\/cat\]/,'</div>').gsub(/(https|http):\/\/qsee.custhelp.com/,'')
			clean_tagline = clean_tagline.html_safe
		end
		clean_tagline
	end

	def video_clean(input)
		video_file = input.match('filename="(.*?)"').to_s.gsub(/filename=/,'').gsub(/"/,'')

		video_folder = input.match('folder="(.*?)"').to_s.gsub(/folder=/,'').gsub(/"/,'')

		video_html = input.gsub(/\[video /,'<div class="text-center embed-responsive embed-responsive-16by9">')

		video_html = video_html.gsub(/filename="(.*?)"/,'')

		video_html = video_html.gsub(/folder="(.*?)"/,'<video class="embed-responsive-item" controls="controls" autoplay="autoplay" poster="'+video_folder+'html5video/'+video_file+'.jpg" style="width:100%" title="recoverpassword" loop="loop" onended="var v=this;setTimeout(function(){v.play()},300)"><source src="'+video_folder+'html5video/'+video_file+'.m4v" type="video/mp4" /><source src="'+video_folder+'html5video/'+video_file+'.webm" type="video/webm" /><source src="'+video_folder+'html5video/'+video_file+'.ogv" type="video/ogg" /><source src="'+video_folder+'html5video/'+video_file+'.mp4" />')

		video_html = video_html.gsub(/\]/,'</video></div>').html_safe

		video_html
	end

	def word_count
		# count = 0
		# count += self.tagline.split.size
		# count += self.title.split.size
		# self.steps.each do |step|
		# 	count += step.step.split.size
		# end
		# count
	end

	def clean_word_count
		# count = 0

		# clean_tagline = HTML::FullSanitizer.new.sanitize(self.tagline)
		# count += clean_tagline.split.size
		# count += self.title.split.size
		# self.steps.each do |step|
		# 	clean_step = HTML::FullSanitizer.new.sanitize(step.step)
		# 	count += clean_step.split.size
		# end
		# count
	end

	def self.to_csv(options = {})
	  CSV.generate(options) do |csv|
	    csv << column_names
	    all.each do |answer|
	      csv << answer.attributes.values_at(*column_names)
	    end
	  end
	end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

	def index
		if !current_user
			redirect_to index2_path
		end
		@answers = Answer.find(:all, :order => 'title ASC')
		@answer = Answer.new
	end

	def inspect_all
		@steps = Step.select('DISTINCT answer_id').where("image_upload_file_name is NULL").order('answer_id')
		render json: @steps
	end

	def inspect
		@answer = Answer.find(params[:id])
		@steps = Step.where('answer_id = ?',params[:id])
		@hash = {}
		@answer.attributes.each do |k,v|
			@hash[k] = v
		end
		@hash['steps'] = @steps
		render json: @hash
	end

	def automate
		@answer = Answer.new
		@answer.automate_answers
	end

	def index2
		if params['jp'] == 'true'
			@answers = Answer.where("translation_needed Like'%COMPLETE%'")
		elsif params['series'] =='newqt'
			@answers = Answer.where("title Like '%NEW QT%'")
		else
			@answers = Answer.find(:all, :order => 'title ASC')
		end
	end

	def index3
		@qc_answers = Answer.where("series = 'QC'", :order => 'title ASC')
		@qt_answers = Answer.where("series = 'QT'", :order => 'title ASC')
		@qr_answers = Answer.where("series = 'QR'", :order => 'title ASC')
		@qs_answers = Answer.where("series = 'QS'", :order => 'title ASC')
		@none_answers = Answer.where("series = 'None'", :order => 'title ASC')
	end

	def qsee_updates
	end
	
	def qsee_rn_array
		@answers = Answer.where('rightnow_answer_id IS NOT NULL')
	end

	def qsee_rn_partial
		@answer = Answer.find(params[:id])
		@steps = Step.where(:answer_id => @answer.id).order(:number,:updated_at)
		render json: { 
	       content: (render_to_string partial: 'angular_answer2', locals: {answer: answer}, layout: false )  
	    } 
	end

	def translate_index
		if !current_user
			redirect_to index2_path
		end
		@answers = Answer.where("translation_needed Like'%YES%'")
	end

	def qtpojo
		@qtpojo = []
		@qtpojo.push(
			{"device" => "Instructions using the NVR/DVR",
			"categories"=>[
				{"category"=>"Recording Setup and Configuration",
				 "answers"=>[
				 	Answer.find(109).pojo, 
				  	Answer.find(107).pojo, 
				  	Answer.find(221).pojo ]
				},
				{"category"=>"Playback",
				 "answers"=>[
				 	Answer.find(225).pojo]
				}, 
				{"category"=>"Backup",
				 "answers"=>[
				 	Answer.find(228).pojo]
				}, 
				{"category"=>"Audio / Mic Setup",
				 "answers"=>[
				 	Answer.find(232).pojo, 
				  	Answer.find(231).pojo]
				}, 
			  	{"category"=>"PTZ Setup",
			  	 "answers"=>[
			  		Answer.find(233).pojo, 
			  	  	Answer.find(235).pojo] 
			  	},
			  	{"category"=>"Firmware Upgrade",
				 "answers"=>[
				 	Answer.find(140).pojo ]
				}, 
				{"category"=>"Email Notification",
				 "answers"=>[
				 	Answer.find(194).pojo]
				}]
			},
			{"device" => "Instructions using the Browser",
			 "categories"=>[
				{"category"=>"Firmware Upgrade",
				 "answers"=>[
				 	Answer.find(121).pojo, 
					Answer.find(117).pojo, 
					Answer.find(13).pojo]
				}, 
				{"category"=>"Setup a Schedule",
				 "answers"=>[
				 	Answer.find(223).pojo, 
				 	Answer.find(222).pojo, 
				 	Answer.find(224).pojo]
				}, 
				{"category"=>"Email Notification","answers"=>[
					Answer.find(195).pojo]
				}, 
				{"category"=>"Playback","answers"=>[
					Answer.find(226).pojo]
				}, 
				{"category"=>"Backup",
				 "answers"=>[ 
				 	Answer.find(229).pojo, 
				 	Answer.find(230).pojo]
				}, 
				{"category"=>"PTZ Setup",
				 "answers"=>[ 
					Answer.find(236).pojo, 
				 	Answer.find(238).pojo] 
				}]
			},
			{"device" => "Instructions using the Mobile App", 
				"categories"=>[
				{"category"=>"Email Notification",
				 "answers"=>[
				 	Answer.find(199).pojo, 
					Answer.find(196).pojo, 
					Answer.find(197).pojo, 
					Answer.find(196).pojo]
				},
				{"category"=>"Playback",
				"answers"=>[
				 	Answer.find(44).pojo, 
				 	Answer.find(46).pojo, 
				 	Answer.find(43).pojo, 
				 	Answer.find(52).pojo] 	
				}]
			})
		render json: @qtpojo
	end

	def preview
		@preview = true
		if params['new']
			@partial2 = true
		else
			@partial2 = false
		end
	 	@answer = Answer.find(params[:id])
  		@steps = Step.where(:answer_id => @answer.id).order(:number,:updated_at)
	end	

	def show
		@answer = Answer.find(params[:id])
	end

	def answer
		@hideMe = true
		@answer = Answer.find(params[:id])
		@steps = Step.where(:answer_id => @answer.id).order(:number,:updated_at)
	end

	def alt_answer
		@hideMe = true
		@answer = Answer.find(params[:id])
		@steps = Step.where(:answer_id => @answer.id).order(:number,:updated_at)
	end

	def answer_jp
		@hideMe = true
		@answer = Answer.find(params[:id])
	end

	def preview_jp
		@preview = true
	 	@answer = Answer.find(params[:id])
  		@steps = Step.where(:answer_id => @answer.id).order(:number,:updated_at)
	end	

	def code
  		@answer = Answer.find(params[:id])
  		@steps = Step.where(:answer_id => @answer.id).order(:number,:updated_at)
  	end

  	def code2
  		@answer = Answer.find(params[:id])
  		@steps = Step.where(:answer_id => @answer.id).order(:number,:updated_at)
  	end

  	def strings
  		@preview = true
  		@answers = Answer.where(:language => "English")
  		@steps = Step.all.sort
  	end

  	def translate
  		if !current_user
			redirect_to index2_path
		end
  		@answer = Answer.find(params[:id])
  		@steps = Step.where(:answer_id => @answer.id)
  	end

  	def spreadsheet
  		@answers = Answer.where(:id => params[:id])
  		@steps = Step.find(:all, :order => 'number')
  		respond_to do |format|
  			format.xls
  		end
  	end

	def new
		@answer = Answer.new
		create
	end

	def create
		@user_id = current_user.id
    	@answer = Answer.new(answer_params)
	    if @answer.save
	      redirect_to edit_answer_path(@answer)
	    else
	      
	    end
	end

	def edit
		@answer = Answer.find(params[:id])
		@step = Step.new
		@steps = Step.where(:answer_id => @answer.id).order(:number,:updated_at)
		@steps_count = @steps.length
		if !current_user
			redirect_to index2_path
		end
	end

	def update
		@answer = Answer.find(params[:id])
	    if @answer.update(answer_params)
	    	flash[:notice] = "Answer successfully updated"
	      	redirect_to edit_answer_path(@answer)
	    else
	      redirect_to :back
	    end
	end

	private

	  def answer_params   
	    params.require(:answer).permit(:language, :series, :tagline, :title, :image, :user_id, :image_upload, :translation_needed, :translation_status, :title_jp, :tagline_jp, :rightnow_answer_id)
	  end
end

app/views/answers/automate.html.erb
automate.html.erb

app/views/answers/code2.html.erb
<div class="container">
	<%= link_to "Back", :back%> |
	<%= link_to "Edit", edit_answer_path(@answer)%> |
	<%= link_to "Preview", angular_path(@answer)%>
	<br><br><br>
	<textarea style="overflow:scroll;width:100%;height:1000px"></textarea>
	<code get-code>
		<%= render 'angular_answer2'%>
	</code>
	<!-- <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.0-rc.0/angular-sanitize.min.js"></script>	
	// <script type="text/javascript" src="/answer.js"></script> -->
	<script type="text/javascript">
		$(document).ready(function(){
			$('textarea').text($('code').html());
		});
		function scrollTop(elemSelector){
		  $('html, body').animate({
		        scrollTop: $(elemSelector).offset().top-80
		    }, 1000)
		};
		scrollTop("body");
	</script>
</div>

app/views/answers/index.html.erb
<style type="text/css">
	body{
		background:lightgrey;
	}
</style>
<div class="container">
	<div class="answer_list col-md-9">
		<h2 class="">Answers</h2>
		<div class="container" role="group">
	      
	    </div>
		<div class="answerList margin">
			<% @answers.each do |answer| %>
				<div class="<%= answer.series %> small bordered">
					<span class="icon "><i class="icon <%= answer.series %>"></i></span>
					<span class="small edit_answer_link"><%=link_to answer.title, edit_answer_path(answer) %></span>
					<span class="pull-right btn-group">
					<% if answer.translation_needed.start_with?("YES")%>
						<img class="pointer Japanese pull-left" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABUAAAANCAMAAABxTNVSAAAAM1BMVEX///+/v7/iCRa4goWtJi66kZS4BxK0Y2jv7++5FyDKoaSvNTzNwMGzVFmqBxGgoKCPj48z3lukAAAAP0lEQVQYlWNgxAYYGBkwAbIoIwemKCsLExs7uigzEwhwookyQQAFolxgQW50N/Dw8rEwY3Evdl8gi/JjCQYBAIMdAQwzbOq2AAAAAElFTkSuQmCC">
						<% if answer.translation_needed.end_with?('COMPLETE)')%>
							<i class="fa fa-file-image-o pull-left"></i>
						<% end %>
					<% end %>	
					<%=link_to "Get Code", code_path(answer), :class => "small btn btn-default btn-modified"%> 
					<%=link_to "Preview", angular_path(answer), :class => "small btn btn-default btn-modified"%>
					</span>
					<br>
				</div>
			<% end %>
		</div>
	</div>
	<div class="new_answer col-md-3 fixed">
	<%= form_for(@answer) do |f| %>
		<a id="hide_new_form" class="hidden-lg hidden-md col-sm-12 col-xs-12">X hide</a>
		<h2 class="">Create a New Answer</h2>
		<div class="form-group hidden">
			<%= f.label "Language:  " %>
		    <%= f.select :language, options_for_select(%w[English]) , :class => "form-control"%>
	    </div>
		<div class="form-group">
			<%= f.label "Series:  " %>
		    <%= f.select :series, options_for_select(%w[QC QT QS QR None]),{}, {:class => "form-control"}%>
		</div>
		<div class="form-group">
			<%= f.label "Title:  "%><br />
		    <%= f.text_area :title, :placeholder => "Title", :class => "form-control"%>
		</div>
		<div class="form-group">
			<%= f.label "Tagline:  "%><br />
		    <%= f.text_area :tagline, :placeholder => "Tagline", :class => "form-control"%>
		</div>
		<div class="form-group">
			<label>RightNow Answer ID:  </label><br />
		    <%= f.text_field :rightnow_answer_id, :placeholder => "RightNow Answer ID", :class => "form-control"%>
		</div>
		
		    <%= f.hidden_field :user_id, :value => current_user.id %>
		    <%= f.hidden_field :translation_needed, :value => 'NO' %>
		    <%= f.hidden_field :translation_status, :value => 'NOT STARTED' %>
	<%= f.submit "Create Answer", :class => "btn btn-default" %>


	<% end %></div>
</div>

app/views/answers/index2.html.erb
<style type="text/css">
	body{
		background:lightgrey;
	}
</style>
<div class="container">
	<div class="answer_list">
		<h2 class="">Answers</h2>
		<div class="btn-group btn-group-lg" role="group" aria-label="Large button group">
	      <button type="button" class="btn btn-default" id="QC">QC Series</button>
	      <button type="button" class="btn btn-default" id="QT">QT Series</button>
	      <button type="button" class="btn btn-default" id="QT_NEW">QT (NEW) Series</button>
	      <button type="button" class="btn btn-default" id="QS">QS Series</button>
	      <button type="button" class="btn btn-default" id="QR">QR Series</button>
	      <button type="button" class="btn btn-default" id="None">Other</button>
	    </div>
		<div class="answerList margin">
			<% @answers.each do |answer| %>
				<div class="<%= if answer.title.match(/NEW QT/) then 'QT_NEW' else answer.series end %> small bordered">
					<span class="icon "><i class="icon <%= answer.series%>"></i></span>
					<span class="small edit_answer_link"><%=link_to answer.title, angular_path(answer) %></span> | 
					<strong><%=link_to 'JSON format', answer_path(answer,:format=>:json) %></strong>
					<span class=" btn-group">
					<% if answer.translation_needed.start_with?("YES")%>
						<img class="pointer Japanese pull-left" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABUAAAANCAMAAABxTNVSAAAAM1BMVEX///+/v7/iCRa4goWtJi66kZS4BxK0Y2jv7++5FyDKoaSvNTzNwMGzVFmqBxGgoKCPj48z3lukAAAAP0lEQVQYlWNgxAYYGBkwAbIoIwemKCsLExs7uigzEwhwookyQQAFolxgQW50N/Dw8rEwY3Evdl8gi/JjCQYBAIMdAQwzbOq2AAAAAElFTkSuQmCC">
						<% if answer.translation_needed.end_with?('COMPLETE)')%>
							<i class="fa fa-file-image-o pull-left"></i>
						<% end %>
					<% end %>	
					<% if !answer.title_fr.blank?%>
						<img class="pointer Japanese pull-left" style="height:13px;width:21px" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA5MDAgNjAwIj4NCjxwYXRoIGZpbGw9IiNlZDI5MzkiIGQ9Im0wLDBoOTAwdjYwMGgtOTAweiIvPg0KPHBhdGggZmlsbD0iI2ZmZiIgZD0ibTAsMGg2MDB2NjAwaC02MDB6Ii8+DQo8cGF0aCBmaWxsPSIjMDAyMzk1IiBkPSJtMCwwaDMwMHY2MDBoLTMwMHoiLz4NCjwvc3ZnPg0K">
					<% end %>	
					</span>
					<%=link_to 'Get Code', code_path(answer),:class=>'pull-right'%>
					<br>
				</div>
			<% end %>
		</div>
	</div>
</div>
<script type="text/javascript">
	$(document).ready(function(){
		$('button.btn').click(function(){
			var buttonClass = "."+$(this).attr('id');
			$('div.answerList '+buttonClass).show();
			$('div.answerList div:not('+buttonClass+')').hide();
			$('div.answerList '+buttonClass+':last').parent().parent().css('border-bottom','3px solid lightgrey')
		});
	});
</script>

app/views/answers/translate_index.html.erb
<style type="text/css">
	body{
		background:lightgrey;
	}
</style>
<div class="container">
    <div class="container-fluid">
        <a class="strong" href="//2.sendvid.com/jcd25zwy.mp4" target="_new">Not sure what to do? Click here to learn how to use this app</a>
    </div>
    <div class="text-center">
        <!-- <span>Total Word Count (no HTML):</span>
        <span class="word_count"></span> -->
    </div>
	<table class="table margin sortable">
    <thead>
      <tr>
        <th>Title</th>
        <!-- <th>Word Count</th>
        <th>Word Count (no HTML)</th> -->
        <th>Translation Status</th>
        <th>Image Status</th>
        <th>Preview Japanese Answer</th>
      </tr>
    </thead>
    <tbody>
    	<% @answers.each do |answer| %>
    	<tr class="bordered">
	    	<td><span class="edit_answer_link"><%=link_to answer.title, translate_path(answer) %></span></td>
	    	<!-- <td><%#= answer.word_count%></td>
            <td><%#= answer.clean_word_count%></td> -->
	    	<td><span class="<%=answer.translation_status%>"><%=answer.translation_status%></span></td>
            <td><span class="<%=answer.translation_needed.gsub(/[()]/,'').gsub(/YES PICTURES/,'')%>"><%=answer.translation_needed.gsub(/[()]/,'').gsub(/YES PICTURES/,'')%></span></td>
            <td><%=link_to "Click here to preview", angular_path(answer)%></td>
    	</tr>
    	<% end %>
    </tbody>
  </table>
</div>
<script type="text/javascript" src="/sort.js"></script>
<!--<script type="text/javascript">
    $(document).ready(function(){
        var count = 0;

        $('.bordered td:nth-of-type(3)').each(function(){
            count += parseInt($(this).text())
        })

        $('.word_count').html(count)
    })
</script>-->