config/routes.rb
Answerbuild::Application.routes.draw do
  root "sessions#new" 
  get 'logout' => 'sessions#destroy', as: :logout
  resources :sessions
  resources :users, except: :destroy
  resources :answers, except: :destroy
  resources :steps

  get 'answers__' => 'answers#index3', as: :index3
  get 'answers_' => 'answers#index2', as: :index2
  get 'automate' => 'answers#automate', as: :automate
  get 'qsee_updates' => 'answers#qsee_updates', as: :qsee_updates
  get 'answers/:id/code' => 'answers#code2', as: :code
  get 'answers/:id/answer' => 'answers#alt_answer', as: :angular
  get 'answers/:id/answer_jp' => 'answers#answer_jp', as: :angular_jp
  get 'answers/:id/inspect' => 'answers#inspect', as: :inspect
  get 'inspect_all' => 'answers#inspect_all', as: :inspect_all
  get 'qsee_rn_array' => 'answers#qsee_rn_array', as: :qsee_rn_array
  get 'qsee_rn_partial/:id' => 'answers#qsee_rn_partial', as: :qsee_rn_partial
  get 'strings' => 'answers#strings', as: :strings
  get 'translate/:id' => 'answers#translate', as: :translate
  get 'translation_portal' => 'answers#translate_index', as: :translate_index
  get 'spreadsheet' => 'answers#spreadsheet', as: :spreadsheet
  get 'answers/:id/preview' => 'answers#preview', as: :preview
  get 'answers/:id/preview_jp' => 'answers#preview_jp', as: :preview_jp
  get 'stepss' => 'steps#index2',as: :imagedump
  get 'qtpojo' => 'answers#qtpojo'

  get 'answers/:id/test' => 'answers#test'

end

app/models/step.rb
class Step < ActiveRecord::Base
	belongs_to :answer
	has_attached_file :image_upload
	has_attached_file :image_upload_jp
	validates_attachment_content_type :image_upload, :content_type => /\Aimage\/.*\Z/
	validates_attachment_content_type :image_upload_jp, :content_type => /\Aimage\/.*\Z/
	validates_presence_of :number, :offset

	def step_number
		true_step_number = self.number - self.offset
		true_step_number
	end	

	def translatable
		ans = Answer.find(self.answer_id)
		if ans.translation_needed == "NO"
			false
		else
			true
		end
	end

	def clean_step
		clean_step = self.step.gsub(/\[red\]/,'<span class="red">').gsub(/\[red\]/,'<span class="red">').gsub(/\[\/red\]/,'</span>').gsub(/\[blue\]/,'<span class="blue">').gsub(/\[\/blue\]/,'</span>').gsub(/\[green\]/,'<span class="green">').gsub(/\[\/reen\]/,'</span>').gsub(/\[yellow\]/,'<span class="yellow">').gsub(/\[\/yellow\]/,'</span>').gsub(/\[orange\]/,'<span class="orange">').gsub(/\[\/orange\]/,'</span>').gsub(/\[lgreen\]/,'<span class="lgreen">').gsub(/\[\/lgreen\]/,'</span>').gsub(/\[bold\]/,'<strong>').gsub(/\[\/bold\]/,'</strong>').gsub(/\[i\]/,'<em>').gsub(/\[\/i\]/,'</em>').gsub(/\[u\]/,'<u>').gsub(/\[\/u\]/,'</u>').gsub(/\[br\]/,'<br>').gsub(/\[note\]/,'<div class="inst information_new"><i class="pull-left fa fa-3x fa-info-circle"></i><span information_text>').gsub(/\[\/note\]/,'</span></div>').gsub(/\[cat\]/,'<div class="inst cautiondiv_new"><i class="pull-left fa fa-3x fa-exclamation-triangle"></i>').gsub(/\[\/cat\]/,'</div>').gsub(/(https|http):\/\/qsee.custhelp.com/,'')
		clean_step = clean_step.html_safe
		clean_step
	end

	def clean_step_jp
		clean_step = self.step_jp.gsub(/\[red\]/,'<span class="red">').gsub(/\[red\]/,'<span class="red">').gsub(/\[\/red\]/,'</span>').gsub(/\[blue\]/,'<span class="blue">').gsub(/\[\/blue\]/,'</span>').gsub(/\[green\]/,'<span class="green">').gsub(/\[\/reen\]/,'</span>').gsub(/\[yellow\]/,'<span class="yellow">').gsub(/\[\/yellow\]/,'</span>').gsub(/\[orange\]/,'<span class="orange">').gsub(/\[\/orange\]/,'</span>').gsub(/\[lgreen\]/,'<span class="lgreen">').gsub(/\[\/lgreen\]/,'</span>').gsub(/\[bold\]/,'<strong>').gsub(/\[\/bold\]/,'</strong>').gsub(/\[i\]/,'<em>').gsub(/\[\/i\]/,'</em>').gsub(/\[u\]/,'<u>').gsub(/\[\/u\]/,'</u>').gsub(/\[br\]/,'<br>').gsub(/\[note\]/,'<div class="inst information_new"><i class="pull-left fa fa-3x fa-info-circle"></i><span information_text>').gsub(/\[\/note\]/,'</span></div>').gsub(/\[cat\]/,'<div class="inst cautiondiv_new"><i class="pull-left fa fa-3x fa-exclamation-triangle"></i>').gsub(/\[\/cat\]/,'</div>').gsub(/(https|http):\/\/qsee.custhelp.com/,'')
		clean_step = clean_step.html_safe
		clean_step
	end

	def clean_step_fr
		clean_step = self.step_fr.gsub(/\[red\]/,'<span class="red">').gsub(/\[red\]/,'<span class="red">').gsub(/\[\/red\]/,'</span>').gsub(/\[blue\]/,'<span class="blue">').gsub(/\[\/blue\]/,'</span>').gsub(/\[green\]/,'<span class="green">').gsub(/\[\/reen\]/,'</span>').gsub(/\[yellow\]/,'<span class="yellow">').gsub(/\[\/yellow\]/,'</span>').gsub(/\[orange\]/,'<span class="orange">').gsub(/\[\/orange\]/,'</span>').gsub(/\[lgreen\]/,'<span class="lgreen">').gsub(/\[\/lgreen\]/,'</span>').gsub(/\[bold\]/,'<strong>').gsub(/\[\/bold\]/,'</strong>').gsub(/\[i\]/,'<em>').gsub(/\[\/i\]/,'</em>').gsub(/\[u\]/,'<u>').gsub(/\[\/u\]/,'</u>').gsub(/\[br\]/,'<br>').gsub(/\[note\]/,'<div class="inst information_new"><i class="pull-left fa fa-3x fa-info-circle"></i><span information_text>').gsub(/\[\/note\]/,'</span></div>').gsub(/\[cat\]/,'<div class="inst cautiondiv_new"><i class="pull-left fa fa-3x fa-exclamation-triangle"></i>').gsub(/\[\/cat\]/,'</div>').gsub(/(https|http):\/\/qsee.custhelp.com/,'')
		clean_step = clean_step.html_safe
		clean_step
	end

end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
	def new
	    @step = Step.new
	    create
  	end
  
  def edit
    @step = Step.find(params[:id])
    
  end

  def index
    # @step= Step.all
    @step = Step.find(params[:id])
    redirect_to edit_step_path(:step)
  end

  def index2
    @answers=Answer.all
    @steps= Step.all
  end

  def update
    
    @step = Step.find(params[:id])
    if @step.update(step_params)
      flash[:notice] = "Step successfully updated!"
      redirect_to :back
    end
  end

  def create

    @step = Step.new(step_params)
    if @step.save
      redirect_to :back
    else
      redirect_to :back
    end
  end

  def destroy
    @step = Step.find(params[:id])

    @step.destroy
    redirect_to(:back)
  end
  
  
  private

  def step_params   
    params.require(:step).permit(:step_type, :number, :step, :answer_id, :image, :offset, :image_upload, :step_jp, :image_upload_jp, :image_upload_fr)
  end

end

app/views/steps/edit.html.erb
<div class="container">
  <%=link_to "Go back to answer", edit_answer_path(@step.answer_id)%>
  <% if flash[:notice] %>
  <div class="notice text-center green">
    <%= flash[:notice] %>
    <span class="btn btn-default hide_notice">X</span>
  </div>
  <% end %>
  <%= form_for(@step, multipart: true) do |f| %>
    <h2>Edit Step</h2>
    <div class="form-group">
      <%= f.label "Step Type:  " %>
        <%= f.select :step_type, options_for_select(%w[Step Information Caution], f.object.step_type),{},{:class => "form-control"}%>
      </div>
    <div class="form-group">
      <%= f.label "Step Number:  " %>
        <%= f.text_field :number, :class => "form-control"%>
    </div>
    <div class="form-group">
      <%= f.label "Step Instruction:  "%><br />
          <div class="form-group color-options">
              <strong><a class="bold">Bold</a></strong> | 
              <em><a class="i">Italic</a></em> | 
              <u><a class="u">Underline</a></u> |
              <a class="red">Red</a> | 
              <a class="blue">Blue</a> | 
              <a class="green">Green</a> | 
              <a class="lgreen">Light Green</a> | 
              <a class="yellow">Yellow</a> |
              <a class="orange">Orange</a> |
              <a class="br"> Add a Break</a> |
              <a class="cat">Caution</a> |
              <a class="note" style="float:none">Information</a> |
              <a class="addLink">Add Link</a>
          </div><br>
              
        <%= f.text_area :step, :placeholder => "Write your instructions here",:class => "form-control"%>
    </div>
    <div class="form-group">
      <%= f.label "Step/Pictures offset  "%><br />
        <%= f.text_field :offset,:class => "form-control"%>
    </div>
      <div class="form-group">
          <%= f.label :image_upload %>
          <%= f.file_field :image_upload, :class => "form-control"%><br>
          <%if @step.translatable%>
            <%= f.label "Japanese Image Upload" %>
            <%= f.file_field :image_upload_jp, :class => "form-control"%>
          <% end %>
          <%= f.hidden_field :image %>
          <% if @step.image!=nil%>
            <input type="button" class="imgClear btn btn-default" value="Click Here to clear the image">
          <% end %>
      </div>
    <%= f.submit "Update Step", :class => "btn btn-default" %>
  <% end %>

  <script type="text/javascript">

    $("p.success").hide();
      $('.color-options a').click(function(){
          var notBold = $(this)[0].className+'][/'+$(this)[0].className+']';
          var isBold = $(this)[0].className+']'
          if ($(this)[0].className=='br'){
              $('#step_step').val($('#step_step').val()+'['+isBold);
          } else{
               $('#step_step').val($('#step_step').val()+'['+notBold);
          }
      });
    // var canvas = new fabric.Canvas('imageCanvas', {
   //     backgroundColor: 'rgb(240,240,240)'
    // });

    $("input.imgClear").click(function(){
      $("#step_image").val("");
    });

    // var imageLoader = document.getElementById('imageLoader');
    // imageLoader.length? imageLoader.addEventListener('change', handleImage, false):console.log();

    // function handleImage(e) {
   //    var reader = new FileReader();
   //    reader.onload = function (event) {
   //        var img = new Image();
   //        img.onload = function () {
   //            var imgInstance = new fabric.Image(img, {
   //                scaleX: 1,
   //                scaleY: 1
   //            })
   //            canvas.add(imgInstance);
   //         }
    //         img.src = event.target.result;

            
   //        finalURI = img.src.replace(/^data:image\/(png|jpg);base64,/, "");

          
    //  $.ajax({
   //            url: 'https://api.imgur.com/3/image',
   //            type: 'post',
   //            headers: {
   //                Authorization: "Client-ID <%= ENV['IMGUR_KEY'] %>"

   //            },
   //            data: {
   //                image: finalURI,
   //                type: 'base64'
   //            },
   //            dataType: 'json',
   //            success: function (response) {
   //                if (response.success) {
                     
   //                    $("#step_image").val(response.data.link.replace('http://',''));
   //                    $("p.success").show();
   //                }
   //            },
   //            error: function (request, status, error) {
   //            window.alert(JSON.parse(request.responseText)["data"]["error"]);
   //            console.log(error);
   //            }
   //        });
          
   //    };
        
    //     reader.readAsDataURL(e.target.files[0]);
    // }
      $(".addLink").on("click", function() {
     $('#imagepreview').attr('src', $(this).find("img").attr('src')); // here asign the image to the modal when the user click the enlarge link
     
     $('#imagemodal').modal('show'); // imagemodal is the id attribute assigned to the bootstrap modal, then i use the show function

     $('button.submit').click(function(){
      $('#step_step').val($('#step_step').val()+'<a href="'+$('input.href').val()+'" target="_blank">'+$('input.text').val()+'</a>');
          $('input.href,input.text').val("");
     });


  });
  </script>
  <div class="modal fade" id="imagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content ">
        <div class="modal-header">
           <h4 class="modal-title" id="myModalLabel">Add Link</h4>
        </div>
        <div class="modal-body">
          <input class="href" data-toggle="tooltip" data-placement="top" data-original-title="Tooltip on top" value="//"><br><br>
          <input class="text" placeholder="Insert Link Text"><br><br>
          <button type="button" class="btn btn-default submit" data-dismiss="modal">Submit</button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/steps/index2.html.erb
<button class="download">Download</button>
<div class="steplinks">
	<% @steps.each do |step| %>
		<img src="//<%= step.image%>" class="img-responsive"><br>
	<% end %>
</div>

<script type="text/javascript">
$(document).ready(function(){
	$('button.download').click(function(){
		var imgArray = $('img.img-responsive');
		     		

		$(imgArray).each(function (i) {
			
	        var $this = $(this);
	        $this.wrap('<a class="temp" href="' + $this.attr('src') + '" download="'+i+'.png" />');
	        $this.click();   
	    });
	});
});
</script>