config/routes.rb
Answerbuild::Application.routes.draw do
  root "sessions#new" 
  get 'logout' => 'sessions#destroy', as: :logout
  resources :sessions
  resources :users, except: :destroy
  resources :answers, except: :destroy
  resources :steps

  get 'answers__' => 'answers#index3', as: :index3
  get 'answers_' => 'answers#index2', as: :index2
  get 'automate' => 'answers#automate', as: :automate
  get 'qsee_updates' => 'answers#qsee_updates', as: :qsee_updates
  get 'answers/:id/code' => 'answers#code2', as: :code
  get 'answers/:id/answer' => 'answers#alt_answer', as: :angular
  get 'answers/:id/answer_jp' => 'answers#answer_jp', as: :angular_jp
  get 'answers/:id/inspect' => 'answers#inspect', as: :inspect
  get 'inspect_all' => 'answers#inspect_all', as: :inspect_all
  get 'qsee_rn_array' => 'answers#qsee_rn_array', as: :qsee_rn_array
  get 'qsee_rn_partial/:id' => 'answers#qsee_rn_partial', as: :qsee_rn_partial
  get 'strings' => 'answers#strings', as: :strings
  get 'translate/:id' => 'answers#translate', as: :translate
  get 'translation_portal' => 'answers#translate_index', as: :translate_index
  get 'spreadsheet' => 'answers#spreadsheet', as: :spreadsheet
  get 'answers/:id/preview' => 'answers#preview', as: :preview
  get 'answers/:id/preview_jp' => 'answers#preview_jp', as: :preview_jp
  get 'stepss' => 'steps#index2',as: :imagedump
  get 'qtpojo' => 'answers#qtpojo'

  get 'answers/:id/test' => 'answers#test'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Answerbuild</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="//fonts.googleapis.com/css?family=Roboto:400,700,300,500|Roboto+Condensed:400,300,700" rel="stylesheet" type="text/css">
  <% if action_name == 'alt_answer'%>
  <link rel="stylesheet" type="text/css" href="//qsee.custhelp.com/euf/assets/themes/qsee/qsee.min.css">
  <% else %>
  <link rel="stylesheet" type="text/css" href="//qsee.custhelp.com/euf/assets/themes/qsee/bootstrap3.css">
  <% end %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet"> 
  <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/trix/0.9.2/trix.css">
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0-rc1/jquery.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<% if action_name == 'manual' || action_name == 'answer' ||action_name == 'qsee_updates'%>
  <body data-no-turbolink="true" class="<%= if !@hideMe then 'preview' elsif action_name == 'answer' then 'no_marg_top' end%>">
<% else %>
  <body style="background:white">
<% end %>
<% if !@hideMe%>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <ul class="nav nav-pills container" role="tablist">
      <% if current_user %>
      <li role="presentation pull-right">
        <a href="<%= if current_user.role=='ADMIN' then '/answers' else '/translation_portal' end%>">
          <img src='//i.imgur.com/2S6kiqI.png'>
        </a>
      </li>
      <li class="presentation pull-right"><%= link_to "Sign Out", logout_path(current_user) %></li>
      <li class="presentation pull-left"><%= if current_user.role=='ADMIN' then link_to "Translations Portal", translate_index_path end%></li>
      <% end %>
    </ul>
  </nav>
<% end %>

<%= yield %>

</body>
  <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular.min.js"></script>
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/angular-strap/2.3.7/angular-strap.min.js"></script>
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/angular-strap/2.3.7/angular-strap.tpl.min.js"></script>
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.0-rc.0/angular-sanitize.min.js"></script>
  <script type="text/javascript" src="/answer.js"></script>  
  
</html>